### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by ondrejbouda** [damejidlo/message-bus#11]
### Maintenance
- [x] logging - separate interface, trait from DJ - #12
- [x] update dependencies #14
- [x] use makefile #14

### Refactoring
- [x] partial unification of message and event bus code (higher abstraction) - middleware supporting message bus #16 

### Better naming
"Event dispatch queue" is unnecessarily busy name and can be misleading. "Dispatcher" is more simple and more common in general. When implementing synchronous event dispatching, this name makes more sense.
- [x] rename event dispatch queue to event dispatcher #16

### Integration test
- [x] happy path integration test #16

### Release version 0.10
- [x] tag
- [x] update message-bus-nette
- [x] update DJ, solve BC breaks
- see https://github.com/damejidlo/message-bus/releases/tag/0.10

### Architecture overhaul

Middleware context:
- [x] introduce explicit callback type instead of closure #18 
- [x] introduce context to enable data sharing between middleware #18 
- [x] implement common middleware supporting message bus with context #18 

Handling through middlleware with context:
- [x] introduce new handling-related functionality leading to better framework integration: separate interafaces for handler type resolving, handler providing and invoking #18 
- [x] introduce new middleware doing these separate tasks, to be able to split them #18 
- [x] use this new middleware in integration test, remove old #19

Other:
- [x] get rid of `SubscriberSpecificDomainEvent` #19
- [x] use middleware supporting message bus also when handling subscriber specific events #19
- [x] unify event "buses" in first and second (sync/async) part of workflow, use common components #19

### Release version 0.11
- [x] tag https://github.com/damejidlo/message-bus/releases/tag/0.11
- [x] update message-bus-nette, solve BC breaks https://github.com/damejidlo/message-bus-nette/pull/11 https://github.com/damejidlo/message-bus-nette/releases/tag/0.11
- [x] update DJ, solve BC breaks

### Release version [0.12](https://github.com/damejidlo/message-bus/releases/tag/0.12)
- [x] revise namespaces - get rid of `Implementation`, `EventBus\IEventDispatcher` is weird etc. #21 
- [x] move validation from nette extension to core library #22

### Release version 0.13
- [ ] how to use without a framework and how to integrate to frameworks
- [ ] revise API
- [ ] confuguration

### Release version 1.0
- [ ] fork away from damejidlo org
- [ ] revise dependencies, lower them if possible
- [ ] docu
